//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XPRES.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adjustment
    {
        public int ID { get; set; }
        public string PID { get; set; }
        public string SEQ { get; set; }
        public string Desc { get; set; }
        public Nullable<double> Qty { get; set; }
        public Nullable<double> ABSQty { get; set; }
        public Nullable<double> UnitCost { get; set; }
        public Nullable<double> NetValue { get; set; }
        public Nullable<double> ABSValue { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> ReqDate { get; set; }
        public Nullable<System.DateTime> CompDate { get; set; }
        public string Type { get; set; }
        public string Status { get; set; }
        public Nullable<int> FileID { get; set; }
        public string ReqID { get; set; }
        public string Requester { get; set; }
    }
}
