//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XPRES.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BomChanx
    {
        public int ID { get; set; }
        public string DR { get; set; }
        public string RevisedItemStatus { get; set; }
        public string RevisedItem { get; set; }
        public string RevisedItemDesc { get; set; }
        public string MorB { get; set; }
        public Nullable<System.DateTime> MIP { get; set; }
        public string ComponentAction { get; set; }
        public string ComponentItem { get; set; }
        public string ComponentDesc { get; set; }
        public string remarks { get; set; }
    }
}
