//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XPRES.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCTracker
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> CountDate { get; set; }
        public string ORG { get; set; }
        public string Subinventory { get; set; }
        public string Locator { get; set; }
        public string PID { get; set; }
        public string Description { get; set; }
        public Nullable<double> SystemQTY { get; set; }
        public Nullable<double> CountedQTY { get; set; }
        public Nullable<double> Difference { get; set; }
        public string Action { get; set; }
        public string Error { get; set; }
        public string FirstCount { get; set; }
        public string SecondCount { get; set; }
        public Nullable<int> Zone { get; set; }
        public Nullable<double> UnitCost { get; set; }
        public string CountStatus { get; set; }
        public Nullable<int> CountID { get; set; }
    }
}
