//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XPRES.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> HireDate { get; set; }
        public Nullable<System.DateTime> TermDate { get; set; }
        public string Title { get; set; }
        public string Dept { get; set; }
        public string Status { get; set; }
        public string Company { get; set; }
        public string XpresAccess { get; set; }
        public string Phone { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public byte[] Picture { get; set; }
        public string FullName { get; set; }
        public string Role { get; set; }
        public Nullable<bool> OutBound { get; set; }
        public Nullable<bool> InBound { get; set; }
        public Nullable<bool> Inventory { get; set; }
        public Nullable<bool> Replen { get; set; }
    }
}
