//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XPRES.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class InboundActivity
    {
        public int Id { get; set; }
        public string PO_LPN { get; set; }
        public Nullable<System.DateTime> Start { get; set; }
        public Nullable<System.DateTime> Finish { get; set; }
        public Nullable<int> LineItems { get; set; }
        public string Operator { get; set; }
        public string CtrlId { get; set; }
        public string Type { get; set; }
        public Nullable<double> LPH { get; set; }
    }
}
