//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XPRES.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MetricsInboundV2
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Main { get; set; }
        public string Sub { get; set; }
        public string Mic { get; set; }
    }
}
