//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XPRES.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MetricsInbound
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string CategoryName { get; set; }
        public string CategoryType { get; set; }
        public Nullable<int> CategoryTreeLevel { get; set; }
        public Nullable<bool> State { get; set; }
        public string Parent { get; set; }
        public string TextValue { get; set; }
        public Nullable<double> NumValue { get; set; }
    }
}
