//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XPRES.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int ID { get; set; }
        public Nullable<int> DeliveryID { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<int> LineCount { get; set; }
        public string Picker { get; set; }
        public Nullable<System.DateTime> AuditStart { get; set; }
        public Nullable<System.DateTime> AuditEnd { get; set; }
        public Nullable<System.DateTime> DeliveryTime { get; set; }
        public Nullable<bool> MultiPick { get; set; }
        public Nullable<int> LPH { get; set; }
        public Nullable<int> PickNum { get; set; }
    }
}
