//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XPRES.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RcvSchedule
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Appt { get; set; }
        public string Carrier { get; set; }
        public Nullable<int> PalletNum { get; set; }
        public Nullable<System.DateTime> Arrive { get; set; }
        public Nullable<System.DateTime> UnloadStart { get; set; }
        public Nullable<System.DateTime> UnloadStop { get; set; }
        public Nullable<System.DateTime> RecStop { get; set; }
        public Nullable<System.DateTime> PutawayStop { get; set; }
        public Nullable<bool> Ltl { get; set; }
        public string ApptID { get; set; }
        public Nullable<int> PoRcvd { get; set; }
        public Nullable<int> PoNotRcvd { get; set; }
        public Nullable<int> PoPtwy { get; set; }
        public Nullable<int> PoNotPtwy { get; set; }
        public Nullable<int> VNC { get; set; }
    }
}
