//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XPRES.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReplenSAAG
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public string Employee { get; set; }
        public Nullable<int> LK00001 { get; set; }
        public Nullable<int> KARDEX { get; set; }
        public Nullable<int> PL { get; set; }
        public Nullable<int> HUBSECURE { get; set; }
        public string CtrlID { get; set; }
    }
}
