//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XPRES.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class XpresEntities : DbContext
    {
        public XpresEntities()
            : base("XpresEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            //throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adjustment> Adjustments { get; set; }
        public virtual DbSet<BomChanx> BomChanges { get; set; }
        public virtual DbSet<CarrierList> CarrierLists { get; set; }
        public virtual DbSet<CCTracker> CCTrackers { get; set; }
        public virtual DbSet<CountSchedule> CountSchedules { get; set; }
        public virtual DbSet<DynamicInbMetric> DynamicInbMetrics { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<InboundActivity> InboundActivities { get; set; }
        public virtual DbSet<MaterialReference> MaterialReferences { get; set; }
        public virtual DbSet<MaterialRequest> MaterialRequests { get; set; }
        public virtual DbSet<MetricsAdj> MetricsAdjs { get; set; }
        public virtual DbSet<MetricsInbound> MetricsInbounds { get; set; }
        public virtual DbSet<MetricsInboundV2> MetricsInboundV2 { get; set; }
        public virtual DbSet<MetricsInv> MetricsInvs { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<ProductionArea> ProductionAreas { get; set; }
        public virtual DbSet<RcvSchedule> RcvSchedules { get; set; }
        public virtual DbSet<ReplenSAAG> ReplenSAAGs { get; set; }
        public virtual DbSet<UnitCost> UnitCosts { get; set; }
        public virtual DbSet<WorkBenchCount> WorkBenchCounts { get; set; }
    }
}
